### ISSUE TITLE
Include files from anywhere on the internet

### ISSUE THREAD

**Issue by ralfw** [GitbookIO/plugin-codesnippet#4]
I'd like to be able to include code from any file on the internet (especially git repositories or gists), eg:

{% codesnippet "https://gist.githubusercontent.com/ralfw/f23c807fb54ceacec47d/raw/65b747556112e4c82bc3127ff72702698694b4bc/01main.groovy", linerange="14-15" %}{% endcodesnippet %}

Which would result in a two line snippet:

```
    mogler.mogeln(
        mogelzettel.&hinzufügen)
```

**Comment by SamyPesse** [comment]
Fixed by 0197186a25dc58802c4308b9df7da2b00085b918

**Comment by ralfw** [comment]
Looking good! Thx for the quick help!
